chore: modernize plugin dependencies
Note that `org.eclipse.mylyn.github:org.eclipse.egit.github.core` in the
current version is a signed jar hence signature gets removed during
shading as otherwise it fails to load in Gerrit with:

  [2023-10-11T12:18:58.433+02:00] [main] WARN  com.google.gerrit.server.plugins.PluginLoader : Cannot load plugin github-plugin
  java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

Change-Id: Ifed1f475d6f9c16be8ccc8f3b9cfc5891db9872b